# Generated by Django 3.2.5 on 2021-07-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='blog',
        ),
    ]
